/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface PsWebComponent {
      'first': string;
      'last': string;
    }
  }

  interface HTMLPsWebComponentElement extends StencilComponents.PsWebComponent, HTMLStencilElement {}

  var HTMLPsWebComponentElement: {
    prototype: HTMLPsWebComponentElement;
    new (): HTMLPsWebComponentElement;
  };
  interface HTMLElementTagNameMap {
    'ps-web-component': HTMLPsWebComponentElement;
  }
  interface ElementTagNameMap {
    'ps-web-component': HTMLPsWebComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'ps-web-component': JSXElements.PsWebComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface PsWebComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;